### ISSUE TITLE
Pipeline management features needed

### ISSUE THREAD

**Issue by fuenfhausen** [Azure/business-process-automation#80]
Please add the following features to allow for managing pipelines:

- Ability to edit a created pipeline
- Ability to delete an existing pipeline
- Ability to rename an existing pipeline

**Comment by jameshoff-msft** [comment]
really good feedback.  adding batch speech to text and then I will work to add these.

**Comment by jameshoff-msft** [comment]
added ability to delete and edit.  rename is tough because I'd need to update all of the data in the db and cog search.  Would probably add more confusion than it solves.
