### ISSUE TITLE
Pipeline monitoring

### ISSUE THREAD

**Issue by fuenfhausen** [Azure/business-process-automation#81]
The current interface does not provide a lot of feedback to a user once they have triggered a pipeline.

Please add the ability to monitor a running pipeline, at a minimum, providing notification when a pipeline has been triggered and when it completes or fails with reference to the failure reason.

**Comment by jameshoff-msft** [comment]
would it be sufficient to have two metrics?  1.) # of times triggered   2,.) # of failures

**Comment by jameshoff-msft** [comment]
I've added a basic Service Bus Monitor to the ingestion screen
